spring.application.name=budgetFlow

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/budgetFlow
spring.datasource.username=postgres
spring.datasource.password=nJemone.0999
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=update