spring.application.name=budgetFlow
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/budget_flow
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
# lokalna Postgres lozinka
spring.datasource.password=nJemone.0999

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.open-in-view=true

jwt.secret=BudgetFlowSecretKey_32chars_OK_2026
jwt.expiration-ms=86400000


#email - ispravka lozinke
# Email
budgetflow.mail.enabled=true
budgetflow.mail.from=financeapp.budgetflow@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=financeapp.budgetflow@gmail.com
spring.mail.password=app_password_od_16karaktera

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
